name: Run Vitest for All Packages

on:
  push:
    branches:
      - main
      - workflow
  pull_request:
    branches:
      - main
jobs:
  build-all:
    name: Build Core, Barcode, PDF, and Component
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm install --workspaces

      - name: Build all packages
        run: npm run build

      - name: Run all Tests
        run: npm run test
